spring:
  profiles:
    active: "prod"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://local-host:9999}
  application:
    name: game-microservice
  datasource:
    url: jdbc:h2:mem:gamedb
  h2:
    console:
      enabled: true
#    username: root
#    password: root
    #url: 'jdbc:h2:mem:gamedb'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
#  gateway:
#    discovery:
#      locator:
#        enabled: true
#        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
#  eureka:
#    client:
#      service-url:
#        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version : 1.0
author:
  name: "eya garali"
  email: "eyagarali26@gmail.com"
